import Header from "@/components/header/header"
import type { Metadata } from "next"
import { Space_Grotesk } from "next/font/google"
import "./globals.css"
import { Suspense } from "react"
import { AnalyticsInfo } from "@/components/analytics-info/analytics-info"
import { AnalyticsInfoSkeleton } from "@/components/analytics-info/skeleton"

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk"
})

export const metadata: Metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable}  antialiased`}
      >
        <Header />
        <main className="p-6 flex flex-col gap-6 pb-24 container mx-auto group">
          <div className="flex flex-col gap-4">
            <h1 className="text-4xl font-black text-black bg-yellow-300 inline-block px-2 py-2 border-4
            border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
              Analytics Info
            </h1>
            <AnalyticsInfo />
            
          </div>
        </main>
        {children}
      </body>
    </html>
  )
}
